[package]
name = "ode-designer-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["imgui"]
imgui = ["dep:imgui-glium-renderer", "dep:imgui-winit-support", "dep:winit", "dep:glium", "dep:imgui"]

[dependencies]
color-eyre = "0.6.2"
derive_more = "0.99.17"
log = "0.4.17"
strum = { version = "0.24.1", features = ["strum_macros", "derive"] }
glium = { version = "0.32.1", optional = true }
imnodes = { path = "./crates/imnodes" }
# odeir = { path = "../odeir" }
thiserror = "1.0.40"
sorted-vec = "0.8.2"

[dependencies.imgui]
version = "0.11.0"
features = ["docking"]
optional = true

[dependencies.imgui-glium-renderer]
version = "0.11.0"
optional = true

[dependencies.imgui-winit-support]
version = "0.11.0"
optional = true

[dependencies.winit]
version = "0.27.5"
optional = true
features = ["wayland", "x11"]
