[package]
name = "ode-designer-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
imgui = ["dep:imgui-glium-renderer", "dep:imgui-winit-support", "dep:winit", "dep:glium", "dep:imgui"]

[dependencies]
color-eyre = "0.6.2"
derive_more = "0.99.17"
log = "0.4.17"
strum = { git = "https://github.com/Syndelis/strum/", branch = "feat/static-variants-array", features = ["strum_macros", "derive"] }
glium = "0.32.1"
imnodes = { path = "./crates/imnodes" }
odeir = { path = "./crates/odeir" }
thiserror = "1.0.40"
sorted-vec = "0.8.2"
linkme = "0.3.15"
paste = "1.0.14"
winit = { version = "0.27.5", features = ["wayland", "x11"] }
imgui = { version = "0.11.0", features = ["docking"] }
imgui-glium-renderer = "0.11.0"
imgui-winit-support = "0.11.0"