version: "3.7"

services:
  appimage-builder:
    command: appimage/scripts/build-appimage.sh
    build:
      context: .
    volumes:
      - ./container-context/target:/ode-designer/target/
      - ./:/ode-designer/
